### ISSUE TITLE
Vereinsvorstellung HS2016 Organisieren

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#13]
**Datum:** Mittwoch, 2016-10-05 10:00 - 15:00

Der [Coredump](https://www.coredump.ch/) ist interessiert an einer Zusammenarbeit; am besten machen wir bei Gelegenheit mal ein Brainstorming was und wie wir alles machen wollen.
## Tasks
- [x] Abklären mit Coredump (Fabian)
- [ ] ...

**Comment by raphiz** [comment]
@fabianhauser müssen wir uns da anmelden oder können wir da einfach auftauchen?

**Comment by fabianhauser** [comment]
@raphiz Wir erhalten vor dem Event noch eine Einladung, darauf müssen wir vermutlich Bescheid geben, wie viel Platz wir brauchen etc.. Wäre gut, wenn wir bis dann schon eine ungefähre Idee haben, was wir machen :)
- Irgend ein Givaway mit unserer Webseite-URL wäre noch cool (evtl. kleinere Stickers?)
- Plakat(e) mit unserem Logo, Domain, Slogan etc.
- Eventuell irgendwas zu Essen oder zu Trinken um die Leute an unseren Stand zu locken :wink:
- ([Der Coredump hatte letztes Jahr u.a. den 3D-Drucker mitgebracht](https://twitter.com/coredump_ch/status/649233894101942272), das ist sicher ein Eye-catcher.)

**Comment by fabianhauser** [comment]
Info von VSHSR:

> Die Infoveranstaltung für die Studenten wird über den Mittag von 11.30 bis 13.10 sein. Es wird wieder im gleichen Rahmen wie letztes Jahr stattfinden, das heisst, jeder Verein bekommt einen Infotisch, wo man mit den Interessierten ins Gespräch kommen kann. Für den Auf- und Abbau haben wir das Zeitfenster von 10.00 - 15.00 Uhr geplant.

Der Coredump Vorstand wurde informiert.

**Comment by raphiz** [comment]
- [x] Plakat mit Logo (mind. A3) (@raphiz?)
- [x] Plakat mit Domain (mind. A3) (@raphiz?)
- [x] Tag Cloud (Linux, An Open Source Projekten mitarbeiten, Open Data ...(@raphiz?)
- [x] Liste mit Bulletpoints: Vision, was wir bisher erreicht haben usw.
- [x] Schoggi (@fabianhauser)
- [x] evtl. Screen um die Website anzuzeigen (oder **einfach mit Laptop**)
- [x] Laptop mit aktueller Mitgliederdatenbank (@fabianhauser)
- [x] Flyer open\HSR (und Flyer Coredump) (Schliessfach @raphiz)

**Comment by raphiz** [comment]
Hier ein kleiner "Spickzettel" um zu wissen, was wir Interessierten erzählen können

> # open\HSR?
> 
> ## Hintergrund
> - Früher alt.comp.hsr - heute open\HSR!
> - "Neuorientierung"
> - Flyer Semesterstart
> 
> ## Unsere Ziele
> - Förderung der Open Source-Kultur und von Open Source-Projekten an der HSR
> - Interessensvertretung an der HSR für die Unterstützung alternativer Betriebssysteme
> - Unterstützung von Einsteigern in der Nutzung von Open Source-Software im Hinblick auf das Studium an der HSR
> 
> ## Mitgliedschaft
> - Setze ein Zeichen
> - wird Teil der Community
> - fördere unser Engagement
> - Du bekommst ein Sticker!
> - 1-2x pro Semester gibt es ein Newsletter
> - Vorrang bei Workshops (falls Plätze limitiert)
> 
> => Mitgliedschaf ist **kostenlos und unverbindlich**.
> 
> ## Mithelfen
> - Rechtschreibprüfung
> - Alternative Software Empfehlungen
> - Testing
> - Dokumentationen schreiben
> - Aktuelle Screenshots
> - Mithelfen bei Events
> - Von uns erzählen
> 
> ## Pläne
> - open\HSR Connect
> - Workshops (Git/Github)

**Comment by rnestler** [comment]
Ich müsste halt freinehmen um teilnehmen zu können für den coredump. Alternativ evt. @dns2utf8?

**Comment by fabianhauser** [comment]
@raphiz : Habe mal die Tasks durchgeschaut und mal alles herausgestrichen, was erledigt oder optional war. Hättest du Zeit, die A3-Unterlagen auszudrucken?

**Comment by fabianhauser** [comment]
Wir müssen uns noch betreffend der Standbesetzung absprechen:

| Zeit | Anwesend |
| --- | --- |
| 11:00 - 12:00 (inkl. Aufbau) | @raphiz |
| 12:00 - 13:00 | @fabianhauser, @olidias |
| 13:00- 14:00 (inkl. Abbau) | @fabianhauser, @murieletrentini |

Vom @openhsr/vorstand haben alle von 11:05 - 11:50 noch C++ Vorlesung.
Könnte den Aufbau & Betreuung bis 11:50 jemand von euch machen? Ich übernehme gerne die Betreuung während der .NET-Vorlesung und den Abbau :wink:

**Comment by raphiz** [comment]
@fabianhauser ich glaube wir haben praktisch alle C++ Vorlesung.
Ich helfe auch gerne während der .NET-Vorlesung
Zu den A3 Unterlagen - klar, kann ich machen (Disclaimer: Keine Haftung auf meine graphische Unfähigkeit :wink: )

**Comment by DennisLigtenberg** [comment]
Auch wenn wir erst seit letzter Woche Mittglieder sind, hätten @InverseIntegral und ich zwischen 11 und 12 Mittagspause. Früher für den Aufbau da sein währe eher schwierig, da haben wir Analysis Vorlesung.

**Comment by murieletrentini** [comment]
Können wir den Aufbau nicht bereits in der 10 Uhr Pause machen?
Ich helfe sonst gern 13.00-14.00

**Comment by raphiz** [comment]
@DennisLigtenberg @InverseIntegral Sehr gerne! Wäre super wenn ihr mithelft und vorbeischaut! :tada: :balloon: 
So wie es aussieht haben sind wir so genügend Leute und so macht es auch mehr Spass!
Danke!

**Comment by raphiz** [comment]
FYI: Vom Coredump wird Coredump Stefan (Tuxle) anwesend sein

**Comment by raphiz** [comment]
## Alle Dokumente sind gedruck!

[logo.pdf](https://github.com/openhsr/verein/files/509146/logo.pdf)
[tag-cloud.pdf](https://github.com/openhsr/verein/files/509145/tag-cloud.pdf)
[url.pdf](https://github.com/openhsr/verein/files/509147/url.pdf)

**Comment by raphiz** [comment]
War ein Erfolg! Fazit: 9 Neue Mitglieder :tada:
