### ISSUE TITLE
Infrastruktur-Flyer für Informatik-Studiernde 2020

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/verein#61]
Der Studiengang Informatik hat uns angefragt, ob wir ein bis zwei A4-Seiten als Einführung in die Infrastruktur für Linux und macOS-Benutzer bis mitte Juni abgeben können. Diese würde allen neu-eintretenden Informatik-Studierenden abgegeben.  
Ich habe mal zugesagt :-)

## Inhalt

Grundsätzlich hatten wir das mal mit dem [Überlebensguide auf unserer Webseite](https://www.openhsr.ch/hsr/) angedacht.

Ich fände ein Cheat-Sheet-Format, auf dem 

1. alle technischen Angaben (z.B. Servernamen etc.), die von der IT nicht klar kommuniziert werden und
2. die ausführlichen Anleitungen in komprimierter Form

abgebildet sind.

## Tasks

- [x] Abklären Infrasturktur-Änderungen (Login, Zweitfaktoren etc.) für die Ost:
  - [x] ~Wo Passwort Wechseln?~ voraussichtlich im Outlook 365 Webmail, weitere Details konnten sie mir aber noch nicht sagen
  - [x] ~WLAN Login~  eduroam
  - [x] ~E-Mail~ IMAP/SMTP wird abgeschaft - es wird nur noch Outlook 365 Online geben (also entweder Webmail oder Outlook als unterstützter Client)
  - [x] ~VPN~ wird vorerst gleich bleiben. Wie das mit neueintretenden Studierenden funktioniert, konnten sie mir noch nicht defintiv sagen.
  - Von folgenden Dingen erwarte ich vorerst keine Änderung: Dateiablagen, Drucken
- [ ] Flyer Erstellen
   - [ ] Format: Inkscape SVG? Scribus?
   - [ ] Layout: Cheat-Sheet-Like?
   - [ ] Inhalte Erfassen
   - [ ] Review
   - [ ] Abgeben Studiengang

**Comment by fabianhauser** [comment]
@LiohMoeller hättest du Zeit, mal mit mir wegen den neuen Dingen für die Ost zu schauen? (siehe Checkliste im Issue)

**Comment by LiohMoeller** [comment]
Klar, können wir machen. Ich bin aber momentan im Homeoffice. Also per Jitsi, Mumble / IRC / XMPP / Matrix oder so. Matrix ID von mir ist `@lioh:feneas.org`, XMPP ist `lioh@trashserver.net`

**Comment by fabianhauser** [comment]
Sorry, ich hatte etwas viel los letzte Woche...

> Klar, können wir machen. Ich bin aber momentan im Homeoffice. Also per Jitsi, Mumble / IRC / XMPP / Matrix oder so. Matrix ID von mir ist `@lioh:feneas.org`, XMPP ist `lioh@trashserver.net`


Das wäre super, @LiohMoeller , würde es dir kommenden Mittwoch (20.06.) um 13:30 auf https://hsr.meet.switch.ch/infra-flyer gehen?

**Comment by LiohMoeller** [comment]
Heute würde es passen.

**Comment by fabianhauser** [comment]
Ich hatte mit den ID kontakt, das Ergebnis ist oben eingetragen.
Vieles ist wohl nach wie vor nicht ganz klar. Einige Infrastruktur wird vorübergehend noch mit dem HSR-Login gehen, und erst später migriert. Neueintretende Studierende erhalten aber nur noch ein Ost-Login (und kein HSR-Login) mehr...

**Comment by fabianhauser** [comment]
Es sieht also so aus, als würde die Unterstützung für andere OS nochmal deutlich verschlechtert (durch das abstellen von IMAP/SMTP).

**Comment by LiohMoeller** [comment]
Kannst ja mal versuchen dagegen zu argumentieren. Mir ist es leider nicht gelungen. Allerdings gibt es alternativen mit denen du hosted Microsoft Mail auch mit Evolution und oauth nutzen kanns. Wie das geht habe ich im OST wiki beschrieben:

https://wiki.ost.ch/display/IOW/Linux

**Comment by LiohMoeller** [comment]
Für mich stellt sich eher die datenschutzrechtliche Frage, denn alle deine Mails liegen bei Microsoft, ob du möchtest oder nicht. Ob das im Sinne einer digitalen Souveränität ist, wage ich zu bezweifeln. Zumal wir ja die entsprechenden Experten hätten, die auch einen in-house Exchange betreiben könnten. Aber das ist alles Politik, nicht meine Baustelle. Wäre dennoch schön, wenn sich dem jemand annehmen würde.

**Comment by fabianhauser** [comment]
@LiohMoeller Leider habe ich keine Rechte auf https://wiki.ost.ch/display/IOW/Linux, könntest du evtl. hier kurz auflisten, was du dort beschrieben hast?

**Comment by LiohMoeller** [comment]
[IOW-15499267-220620-1434-64.pdf](https://github.com/openhsr/verein/files/4813188/IOW-15499267-220620-1434-64.pdf)

**Comment by LiohMoeller** [comment]
Ist leider nicht erlaubt, da es sensitive Informationen enthält und darf so wohl auch nicht im OpenHSR Wiki publiziert werden. Ansonsten das kommerzielle Eule Plugin für TB verwenden.

**Comment by das-g** [comment]
> @LiohMoeller Leider habe ich keine Rechte auf https://wiki.ost.ch/display/IOW/Linux, könntest du evtl. hier kurz auflisten, was du dort beschrieben hast?

> Ist leider nicht erlaubt, da es sensitive Informationen enthält und darf so wohl auch nicht im OpenHSR Wiki publiziert werden. Ansonsten das kommerzielle Eule Plugin für TB verwenden.

Inwzischen kann ich auf https://wiki.ost.ch/display/IOW/Linux zugreifen. Nehme an, das gilt für alle mit OST-Account?

Bzgl. E-Mail-Client-Einrichtung (bislang nur Evolution) scheint die Unterseite [Linux | Wie richte ich mein Email-Postfach und meinen Kalender ein?](https://wiki.ost.ch/pages/releaseview.action?pageId=15499267) relevant zu sein.

**Comment by das-g** [comment]
Ein Flyer "open\HSR Quickstart-Guidefür Linux und macOS an der Ost" wurde letztes Jahr erstellt und glaub' tatsächlich an die neueitretenden Studierenden verteilt:
https://github.com/openhsr/verein/tree/master/design/flyers/quickstart-ost

Handelt es sich dabei um den in diesem Issue angedachten Flyer?

**Comment by LiohMoeller** [comment]
Ja, alle mit OST-Account können darauf zugreifen.

**Comment by fabianhauser** [comment]
> Ein Flyer "open\HSR Quickstart-Guidefür Linux und macOS an der Ost" wurde letztes Jahr erstellt und glaub' tatsächlich an die neueitretenden Studierenden verteilt:
> https://github.com/openhsr/verein/tree/master/design/flyers/quickstart-ost
> 
> Handelt es sich dabei um den in diesem Issue angedachten Flyer?

Ja genau! Hab wohl vergessen, dieses Issue zu schliessen.
